name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install package and dev dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # Install the package in editable mode with dev dependencies
        pip install -e ".[dev]"
        # Show installed packages for debugging
        pip freeze
    
    - name: Show package structure
      run: |
        echo "Project structure:"
        find . -type f -name "*.py"
    
    - name: Run pytest
      run: |
        echo "Running tests with pytest..."
        pytest -v tests/ --tb=short

    - name: Run linting checks
      if: always()  # Run even if tests fail
      run: |
        echo "Running flake8..."
        flake8 src tests --count --show-source --statistics
        
        echo "\nChecking black formatting..."
        black --check --diff src tests
        
        echo "\nChecking import sorting..."
        isort --check-only --diff src tests