name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Debug Environment
      run: |
        echo "Current directory:" && pwd
        echo "\nDirectory contents:" && ls -la
        echo "\nPython location:" && which python
        echo "\nPython version:" && python --version
        echo "\nPIP version:" && pip --version
    
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest pytest-asyncio
    
    - name: Install package
      run: |
        python -m pip install -e .
        echo "\nInstalled packages:" && pip list
    
    - name: Verify package structure
      run: |
        echo "Project structure:"
        find . -name "*.py" -type f
        echo "\nPython path:" && python -c "import sys; print('\n'.join(sys.path))"
        echo "\nTry importing package:" && python -c "import lingualearn; print('Success!')"
    
    - name: Run pytest
      run: python -m pytest -v tests/